### ISSUE TITLE
Add the ability to normalize by the country population

### ISSUE THREAD

**Issue by jonadem** [boogheta/coronavirus-countries#1]
Functionality available here ("normalize to population") : https://covid-stats.theo.io/dashboard_draggable.php

PS: Thank you for your work ! ;-)

**Comment by boogheta** [comment]
Yes! It's definitely one of the top features in the todo pile! Thanks for tjhe feedback :)

**Comment by boogheta** [comment]
TODO:
- [ ] Gather data for all agregated countries
- [ ] add menu entry to switch between absolute values and in percentage of population

**Comment by robindemourat** [comment]
Here is a compilation of the populations by country and provinces for related countries: https://docs.google.com/spreadsheets/d/1e703pe3GmBQt0i2yAOS0F6Bhxy91U1-NTB6JMRSTzc0/edit?usp=sharing

**Comment by boogheta** [comment]
JHU's data is adding new provinces and countries when new ones are reported, so the list will need to be completed from time to time @robindemourat 
Here are the few missing as of tonight:
```
WARNING: missing population for Canada / Northwest Territories
WARNING: missing population for Canada / Recovered
WARNING: missing population for Canada / Yukon
WARNING: missing population for World / Saint Kitts and Nevis
WARNING: missing population for World / Mali
WARNING: missing population for World / Guinea-Bissau
WARNING: missing population for World / Kosovo
WARNING: missing population for World / West Bank and Gaza
WARNING: missing population for World / MS Zaandam
WARNING: missing population for World / Burma
```

**Comment by jonadem** [comment]
Great ! Thank you
