### ISSUE TITLE
Deprecated JHU data

### ISSUE THREAD

**Issue by adkinsanalytics** [boogheta/coronavirus-countries#15]
Source data possibly needs to be updated - I noticed that UK deaths numbers are identical for the last two days.

Readme.md at https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series states:

> ---DEPRICATED WARNING---
> The files below will no longer be updated. With the release of the new data structure, we are updating our time series tables to reflect these changes. Please reference time_series_covid19_confirmed_global.csv and time_series_covid19_deaths_global.csv for the latest time series data.
> 
> time_series_19-covid-Confirmed.csv
> time_series_19-covid-Deaths.csv
> time_series_19-covid-Recovered.csv

Figures in time_series_covid19_deaths_global.csv are correct (as per readme warning).

**Comment by boogheta** [comment]
Ha, bad news, thanks for reporting it, I didn't notice :/
This means there won't be any more data on their site on recovered cases anymore, too bad, will see what is the best approach, probably drop recovered and currently sick for now then :/
