### ISSUE TITLE
Complete missing population data

### ISSUE THREAD

**Issue by boogheta** [boogheta/coronavirus-countries#22]
JHU's data is adding new provinces and countries when new ones are reported, so the list will need to be completed from time to time @robindemourat 
Here are the few missing as of tonight:
```
WARNING: missing population for Canada / Northwest Territories
WARNING: missing population for Canada / Recovered
WARNING: missing population for Canada / Yukon
WARNING: missing population for World / Saint Kitts and Nevis
WARNING: missing population for World / Mali
WARNING: missing population for World / Guinea-Bissau
WARNING: missing population for World / Kosovo
WARNING: missing population for World / West Bank and Gaza
WARNING: missing population for World / MS Zaandam
WARNING: missing population for World / Burma
```

https://docs.google.com/spreadsheets/d/1e703pe3GmBQt0i2yAOS0F6Bhxy91U1-NTB6JMRSTzc0/edit?usp=sharing

_Originally posted by @boogheta in https://github.com/boogheta/coronavirus-countries/issues/1#issuecomment-605720022_

**Comment by robindemourat** [comment]
The data was just updated. New column was added for mentionning additional sources used to retrieve some populations.

- [X] Canada / Northwest Territories
- [ ] Canada / Recovered
- [X] Canada / Yukon
- [X] World / Saint Kitts and Nevis
- [X] World / Mali
- [X] World / Guinea-Bissau
- [X] World / Kosovo
- [ ] World / West Bank and Gaza
- [X] World / MS Zaandam
- [X] World / Burma

Isn't the "Canada / Recovered" territory a glitch in the data ?

**Comment by boogheta** [comment]
It looks like it yes, will investigate!
Thanks for all the rest!

**Comment by boogheta** [comment]
So I confirm, this is an issue on the source side, reported already by different people here: https://github.com/CSSEGISandData/COVID-19/issues/1800

WIll hardfix it in the data download on our side

**Comment by robindemourat** [comment]
@boogheta I confirm it does not come from the population column (it was a footnote in the scraped source) !

**Comment by boogheta** [comment]
I proposed a PR at the source https://github.com/CSSEGISandData/COVID-19/pull/1816
Hardfixing it for now

**Comment by boogheta** [comment]
Fixed in 008d7a6fdadbca3683ee5b630667c571a961f1b2
(and added population data for Botswana newly appeared)

**Comment by boogheta** [comment]
In prevision of current work in progress on #10, we're gonna need more population data for some countries regions, so I'm reopening this with a checklist that I will complete progressively.
- [ ] Italy / Abruzzo
- [ ] Italy / Basilicata
- [ ] Italy / P.A. Bolzano
- [ ] Italy / Calabria
- [ ] Italy / Campania
- [ ] Italy / Emilia-Romagna
- [ ] Italy / Friuli Venezia Giulia
- [ ] Italy / Lazio
- [ ] Italy / Liguria
- [ ] Italy / Lombardia
- [ ] Italy / Marche
- [ ] Italy / Molise
- [ ] Italy / Piemonte
- [ ] Italy / Puglia
- [ ] Italy / Sardegna
- [ ] Italy / Sicilia
- [ ] Italy / Toscana
- [ ] Italy / P.A. Trento
- [ ] Italy / Umbria
- [ ] Italy / Valle d'Aosta
- [ ] Italy / Veneto

**Comment by robindemourat** [comment]
I just added France's *départments* and Italy's *province* in a [populations spreadsheet](https://docs.google.com/spreadsheets/d/1e703pe3GmBQt0i2yAOS0F6Bhxy91U1-NTB6JMRSTzc0/edit?usp=sharing) - I was not able to check if it is 100% aligned but it seems so mostly.

**Comment by boogheta** [comment]
Thank you!!
