### ISSUE TITLE
Broken rounding of numbers

### ISSUE THREAD

**Issue by martin-t** [boogheta/coronavirus-countries#26]
Some numbers appear multiple times - it rounds to larger numbers than the step.

![Screenshot_20200331_113436](https://user-images.githubusercontent.com/4079823/78011341-c0086480-7343-11ea-9b5b-7f16ef55593a.png) ![Screenshot_20200331_113510](https://user-images.githubusercontent.com/4079823/78011352-c39beb80-7343-11ea-93b3-8cbc5b09ac4f.png)

**Comment by boogheta** [comment]
Ha yes indeed, well caught thx for the bug report, I think I know where the problem comes from.
Could you share the urls where it happened for easier testing?

**Comment by boogheta** [comment]
should be fixed now, can you please check on your side (after hard refresh of the page)

**Comment by martin-t** [comment]
Yeah, it's fixed, thanks. The urls are

https://boogheta.github.io/coronavirus-countries/#confirmed&places=Australia,Czechia,Estonia,France,Germany,India,Iran,Italy,Japan,Slovakia,South%20Korea,Spain,Switzerland,USA,United%20Kingdom

https://boogheta.github.io/coronavirus-countries/#deceased&places=China,France,Iran,Netherlands,Spain,USA,United%20Kingdom

but of course the values will change every day.
