### ISSUE TITLE
Stack mode

### ISSUE THREAD

**Issue by eduardoleitaocruz** [boogheta/coronavirus-countries#37]
when you switch from 'series' to 'stack' the order of colors doesn't match the countries.

**Comment by boogheta** [comment]
Hello, and thanks for the report!
Yes i noticed this as well and fixed it in the development branch in progress which i will probably release early next week!
I leave this issue open until then and will let you close it by then if you confirm!

**Comment by boogheta** [comment]
Here it is! Please check if your issue still applies, thanks!
