### ISSUE TITLE
Error consolidating UK data

### ISSUE THREAD

**Issue by aramse** [boogheta/coronavirus-countries#41]
Running the `consolidate_uk.py` file is returning the following error:

```
$ ./bin/consolidate_uk.py > data/uk.csv
Traceback (most recent call last):
  File "./bin/consolidate_uk.py", line 55, in <module>
    print(",".join([d, b, str(countries[b]["confirmed"][i]), str(countries[b]["deceased"][i])]))
IndexError: list index out of range
```

**Comment by boogheta** [comment]
Well caught, this was due to some change in England's historical data that was improved by @TomWhite and badly handled on my side.
Thanks for the report!

**Comment by aramse** [comment]
@boogheta I'm seeing the same error again since yesterday.

**Comment by boogheta** [comment]
Yes indeed, thanks again @aramse.
The data was improved again, now tests are complete and I could integrate them as well, although it looks to me like there are some weird values for England and UK total at the source, I took an arbitrary choice in the mean time and reported it here https://github.com/tomwhite/covid-19-uk-data/issues/52

**Comment by boogheta** [comment]
Hi @aramse,
I don't have any issue with the app being replicated slighly modified, this is open source.
Although, it does have a specific open source licence ([AGPL v3](https://github.com/boogheta/coronavirus-countries/blob/master/LICENSE)) which supposes to respect a few rules when you do so. Among which it minimally requires you to:
- attribute properly (so a link to the médialab website won't suffice, you need to give links to the original app and its code, with the original name of the app and of the authors, meaning me from médialab and not only médialab)
- redistribute the sourcecode of any public instance released, meaning the code of your fork shall  be also released as opensource on some public git repository and linked to from your platform
Thanks in advance!

**Comment by aramse** [comment]
Great will look to do make the needed modifications to comply here, thank you!

**Comment by aramse** [comment]
Updated to better comply 🙂
