### ISSUE TITLE
Check Spain data

### ISSUE THREAD

**Issue by boogheta** [boogheta/coronavirus-countries#44]
NOTAs announce:
```
El objetivo de los datos que se publican en esta web es saber el número de casos acumulados a la fecha y que por tanto no se puede deducir que la diferencia entre un día y el anterior es el número de casos nuevos ya que esos casos pueden haber sido recuperados de fechas anteriores. Cualquier inferencia que se haga sobre las diferencias de un día para otro deben hacerse con precaución y son únicamente la responsabilidad del autor.,,,,,,,,
Los datos de estas comunidades son datos de prevalencia (personas ingresadas a fecha de hoy). No reflejan el total de personas que han sido hospitalizadas o ingresadas en UCI  a lo largo del periodo de notificación(CL(UCIs)-GA(UCIS)-CM*-MD**),,,,,,,,
* Desde el día 11/04/2020 las cifras de hospitalizados de CM son casos acumulados. Previamente se refieren a personas ingresadas ese día.,,,,,,,,
* Desde el día 12/04/2020 las cifras de UCIs de CM son casos acumulados. Previamente se refieren a personas ingresadas ese día.,,,,,,,,
* Desde el día 26/04/2020 las cifras de Hospitalizados y UCIs de CM son casos acumulados. Previamente se refieren a personas ingresadas ese día. Se actualizará la serie cuando esté disponible,,,,,,,,
NOTA2:Se excluyen de la serie las notificaciones de personas  con anticuerpos positivos sin síntomas en el momento de realización de la prueba en los que no se puede establecer un momento de contagio ni si han padecido o no la enfermedad.,,,,,,,,      
```
There are also issues with confirmed cases values which are not reported anymore on many lines
This can be seen for instance here: https://boogheta.github.io/coronavirus-countries/#country=Spain&confirmed&recovered&hospitalized&intensive_care&deceased&log&multiples&places=Castilla%20La%20Mancha,Entire%20Spain,Galicia,Madrid&alignTo=deceased

**Comment by aramse** [comment]
Not sure if this is the same issue, but Spain data has recently shown a huge 1-day spike in currently sick numbers: https://boogheta.github.io/coronavirus-countries/#currently_sick&ratio&places=France,Germany,Italy,Spain,Turkey,USA,United%20Kingdom&alignTo=deceased

**Comment by boogheta** [comment]
Hi, it looks like it's the number of Spain recovered cases which has been set to 0 by error today, I guess this shall be fixed tonight with today's update

**Comment by aramse** [comment]
Hello again! It seems that the upstream link below now returns a 404:

https://covid19.isciii.es/resources/serie_historica_acumulados.csv

**Comment by boogheta** [comment]
indeed :(
I don't speak Spanish very well, do you know of a good new source for Spain regions?
The new files available on the official Spanish governmental source <https://cnecovid.isciii.es/covid19/#documentación-y-datos> seem to only propose number of cases with the type of tests performed <https://cnecovid.isciii.es/covid19/resources/casos_diagnostico_ccaa.csv>, and details from hospitals by provincia <https://cnecovid.isciii.es/covid19/resources/casos_hosp_uci_def_sexo_edad_provres.csv> but i cannot seem to find deceases cases
