### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [boogheta/coronavirus-countries#48]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/FW5FB6
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by boogheta** [comment]
Hi and thanks for the registration.
Although I'm not sure registering the dataset of this dashboard is very useful: it is only an agregation of various more official datasets available elsewhere, for which I don't have much more information on the metadata. You can find the urls of all sources by searching the word "source" in the file there: https://github.com/boogheta/coronavirus-countries/blob/master/bin/export-main-countries.py
