### ISSUE TITLE
Fetch and display vaccination status

### ISSUE THREAD

**Issue by luciusf** [boogheta/coronavirus-countries#50]
The Coronavirus Country Comparator is my goto solution to really understand what's happening in the world. Longterm trends are best visible in this app. 

Therefore it would be great to also be able to look at "vaccination" graph (if such data can be obtained easily). 

Ideally, this could be combined with an additional "immunity" graph, which takes both vaccination and former infections into account. 

In any way: Thanks for this tool!

**Comment by boogheta** [comment]
Hello @luciusf and thanks for reaching out.
This is indeed something I would like to include, although I didn't find much time to work on this project in the past few months and I haven't taken the time to search for an aggregated worldwide dataset of vaccine numbers per country yet. Do you know of such a dataset available somewhere?
The aim of this tool is to propose an interface to visualise worldwide data built by others, I don't want to invest myself in building the data myself as I won't be able to ensure its long term maintenance (contrary for instance to Johns Hopkins that does a wonderful job with the cases/deceased data for all countries)

**Comment by luciusf** [comment]
Hi @boogheta, thanks for the reply!

There is a fellow countryman of yours (fellow cityman actually), [Edouard Mathieu](https://github.com/edomt), who compiles recent covid data including vaccination stats. He is publishing it as [csv and json directly on github](https://github.com/owid/covid-19-data/tree/master/public/data). According to the repo, all data is licensed under the CC BY. I only quickly skimmed over the data, but from what I see, it would make a nice complementary addition to what you offer already. It wouldn't leave any blanks or be too specific to just a handful of countries.

**Comment by luciusf** [comment]
The more I look at the data collection from edomt, the more I'm thinking, that this could actually be used as a full data source replacement for your app. edomt is incorporating all the John Hopkins data which you currently use, but is enriching it not only with information about vaccination, but also about ICUs among other things. 

The only downside could be, that due to the "man" in the middle, the recent data would trickle down a bit later. This would completely ok for my use case, as I'm interested in understanding the trends. 

Unfortunately it is not braking down the numbers into age groups, which would be interesting to see. I read elsewhere, that the vaccination impact could already been seen in the vaccinated 80+ group, with their trends falling contrary to the unvaccinated groups. But that's another topic.

**Comment by boogheta** [comment]
Interesting thanks, will try and see if that's doable in the coming days/weeks then!

**Comment by RouxRC** [comment]
Our World in Data seems like a good global source for vaccines: https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations
